### ISSUE TITLE
Fonts "disappearing" on main and settings screen

### ISSUE THREAD

**Issue by hillbicks** [jurialmunkey/skin.arctic.zephyr.2#116]
Hi,

from time to time I'm missing fonts when using arctic zehpyr 2. Acutally, I already had that problem with version 1 as well. 
I'm using the repository from here, so I'm on the latest version. It happens with the light and dark theme. 

Here are two examples:
1) one menu option is missing the font, but the actual menu is still there and can be chosen. Most commonly happens with live tv. 
2) when opening the settings, some of the main menu options on the left are visible, others are missing. Same goes for the inidividual settings on the right side. 

I can not reliably reproduce the issue, but there is a way to fix this. Change the skin to the default kodi skin and back to arctic zephyr2 fixes the issue. 

I couldn't see any entries in the log that would shed some light on the cause for this error. 

Previously I was using arch with kodi and the arctic zephyr repo, but this also happens with the latest version of libreelec on a raspberry pi4. 

If I can provide further information for this, please let me know.

**Comment by jurialmunkey** [comment]
Is it only some text that is missing or all text?

Do you use profiles? There is a long standing Kodi bug where profiles do not load skin strings correctly on first load - this bug exists for all skins that aren't Estuary. The only solution is for the user to reload the skin (shortcut from power menu - press "S" on keyboard).

If it is the profiles bug, then you can create an autoexec.py file to reload the skin automatically:
https://forum.kodi.tv/showthread.php?tid=339414&pid=2810200#pid2810200

The bug will be fixed in next Kodi version (Matrix v19).
https://github.com/xbmc/xbmc/pull/16420

**Comment by hillbicks** [comment]
Thanks, that seems to be it. Never occured to me that this might be a problem of kodi.

I appreciate the help and moreso the work on the arctic zephyr 2 skin, it looks fantastic. 
Thanks again!
