### ISSUE TITLE
[Style] Watched Indicator Color

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.zephyr.2#138]
Would it be possible to have the watched indicators and counts stay white when they're selected? They are white when not selected, but turn black when selected, which doesn't give very much contrast with most highlight colors, so they're very hard to read, especially at a distance.

**Comment by jurialmunkey** [comment]
I made it black because I felt it had better contrast overall, plus it also means that I don't need to do a colour switch between using white highlight and other colours.

Compare the following images. In some cases the white provides better contrast. However, in others it is very difficult to see (e.g. the lime green) whereas the black always has an adequate level of contrast.

![01](https://user-images.githubusercontent.com/4618719/68986821-97417000-0877-11ea-8a38-04a1c206b682.jpg)
![02](https://user-images.githubusercontent.com/4618719/68986822-97417000-0877-11ea-89e6-48352fc9ba49.jpg)
![03](https://user-images.githubusercontent.com/4618719/68986823-97417000-0877-11ea-803f-0457bd91209e.jpg)
![04](https://user-images.githubusercontent.com/4618719/68986824-97da0680-0877-11ea-91af-09cbbeb39a30.jpg)
![05](https://user-images.githubusercontent.com/4618719/68986825-97da0680-0877-11ea-9ca3-76a9a37313ed.jpg)
![06](https://user-images.githubusercontent.com/4618719/68986826-97da0680-0877-11ea-9c17-1a06d59b81b0.jpg)
![07](https://user-images.githubusercontent.com/4618719/68986827-98729d00-0877-11ea-96db-df50e5cb6403.jpg)
![08](https://user-images.githubusercontent.com/4618719/68986829-98729d00-0877-11ea-9e17-4b20c863e6f6.jpg)

**Comment by drinfernoo** [comment]
Ah, crap, those are some pretty good examples. Maybe my eyes are just bad 😂 I tend to use the dark theme, with a relatively dark highlight color (certainly not as vibrant as any of the examples, as I'm using #00796B right now), and black just seems very hard to see in that instance.

**Comment by jurialmunkey** [comment]
I would think that you are probably the outlier in this case - I would expect most people to pick colours on the brighter end of the spectrum. Ideally I would match to the brightness of selected colour but there isn't any easy way to do it. I'll think about adding an option to flip the colours but I am wary of adding too many extra options for what are likely corner cases.

**Comment by notoco** [comment]
make the advanced settings section, visible only in expert settings mode in kodi. then the advanced user will be able to change himself, and the ordinary user will not even search.

**Comment by jurialmunkey** [comment]
> 
> 
> Make for example the advanced settings section, visible only in expert settings mode in kodi. Then the advanced user will be able to change himself, and the ordinary user will not even search.

Having a place for options is not the issue. The issue is that adding more options makes the code more complex. The more complex the code gets, the harder it is to maintain and it becomes a chore to develop the code further. Since I do all this for free, that's a pretty quick way to get me to abandon the skin because I just end up maintaining a bunch of options that I don't use and having to ensure backwards compatibility whenever I want to add new features.

**Comment by notoco** [comment]
Approx. You're right. The skin is practically perfect in its simplicity, so let it stay better. If someone changes something, they can do it themselves (as I do for my and my family's needs)
