### ISSUE TITLE
Keep getting skin shortcuts error

### ISSUE THREAD

**Issue by tapwizard** [jurialmunkey/skin.arctic.zephyr.2#144]
[kodi.log](https://github.com/jurialmunkey/skin.arctic.zephyr.2/files/3907672/kodi.log)
Kodi 18.5 Windows 10. I'm trying to use this skin and every time I added my wizard (openwizard) it would state errors in log. Log would state: AttributeError: 'NoneType' object has no attribute 'getProperty'. I thought this was wizard related however I tried a fresh install of kodi with only your repo and marcelveldts and just deleting some of the skins menu defaults and changing sub menu a little bit the error appears again in log. No error notification popped up, the only way I knew was my wizard would report there were errors in log. everything is latest versions. Thanks for any help.

**Comment by jurialmunkey** [comment]
Does this error stop the skin from working?

Also, I don't maintain skinshortcuts add-on...

**Comment by tapwizard** [comment]
As far as I can tell the skin still functions, just the wizard reporting constant errors. I posted the issue on bignoids GitHub also. Didn't know who to contact about issue because I tried another skin that uses skinshortcuts and there was no issue with that skin, so I figured I'd let everyone know. Thanks.

**Comment by jurialmunkey** [comment]
Skinshortcuts is currently not officially maintained by anyone. However, mikeSilvo is working on a PY3 compatible version for Matrix: https://forum.kodi.tv/showthread.php?tid=178294&pid=2880843#pid2880843

I use a lot of the more advanced features of skinshortcuts in AZ2 so that's probably why you wouldn't get the errors in another skin.

If you figure out what changes cause the errors, let me know and I'll try to reproduce them on my end to see what is causing them.

**Comment by tapwizard** [comment]
Alright, thanks.  I have just verified that the estuary mod skin from blamo gets the same error doing the same thing so its not just Arctic Zephyr 2 skin. His skin is also using 1.0.18.

**Comment by tapwizard** [comment]
Thanks for info about mike silvo. This issue is well documented on his GitHub isuues.
