### ISSUE TITLE
Ratings missing from most ViewTypes

### ISSUE THREAD

**Issue by brentonv** [jurialmunkey/skin.arctic.zephyr.2#149]
Dear sir. You have created a fantastic skin however when I switch ViewTypes it is missing ratings on most of them. Please include an option for this if at all possible. 

Also there seems to be unnecessary data displayed under widgets. If you select a widget without metadata it displays "N/A" and a repeat of the title underneath.

Could you please include an option to turn off the Movie/TV info that propogates underneath widgets and also a ClearLogo header option here would be cool.

Thirdly I find that 'info-lists' does nothing. Perhaps I'm not using the correct display. I only use home screen widgets for scraping Trakt and standard ViewTypes for libraries.

Thanks for the great add-on!

**Comment by jurialmunkey** [comment]
> when I switch ViewTypes it is missing ratings on most of them. Please include an option for this if at all possible.

The skin is minimalistic. If a view lacks ratings, it is intentional. The views without ratings lack either adequate horizontal or vertical space to display ratings in a way that I would be happy with.

> Also there seems to be unnecessary data displayed under widgets. If you select a widget without metadata it displays "N/A" and a repeat of the title underneath.

Option to disable single widget info is planned.

> Thirdly I find that 'info-lists' does nothing. Perhaps I'm not using the correct display. I only use home screen widgets for scraping Trakt and standard ViewTypes for libraries.

I'm not sure what you mean here. Info lists are the lists displayed when pressing down in the information dialog. The option in settings allows you to disable lists that you don't use to avoid unnecessary loading.

**Comment by brentonv** [comment]
Oh ok info lists when pressing down yeah thought so but wasn't entirely certain. Can't you please please add rating next to the year. Heaps of room😊

**Comment by AmineI** [comment]
> The skin is minimalistic. If a view lacks ratings, it is intentional. The views without ratings lack either adequate horizontal or vertical space to display ratings in a way that I would be happy with.

I think the way you handled "episodes left to watch" indicator for shows was pretty neat, but coming from the default estuary skin I had to get used to that indicator not displaying the rating.
![image](https://user-images.githubusercontent.com/15179425/72548798-be281c80-388f-11ea-8e60-e85e9e162453.png)


One possible solution to keep the skin minimalistic while still displaying this information would a setting to display the rating instead of the number of episodes left to watch, in this indicator - since the "left to watch" indicator is not relevant for movies or watched shows for example.  I think it'd be a great addition, as when choosing a movie to rewatch or watch with friends I used to check the rating I gave it as well on estuary .

I saw however that you didn't wish to have too many options as it easily makes it hard to maintain, which I definitely understand ! So it's no big deal if you prefer to keep it this way obviously :) .
