### ISSUE TITLE
[Request] Display Plot Overlay

### ISSUE THREAD

**Issue by brentonv** [jurialmunkey/skin.arctic.zephyr.2#152]
Request for enhancement of plot overlay feature to (1) press down displays remaining plot and (2) press down at end of plot returns to previous item.

(1) When plot is larger than the screen the remaining plot is missing. Pressing down does work in info view but not in library.

(2) For example at the moment if I browse a Trakt list and plot overlay shows, when I press down to return to the Trakt list it goes down further to the scroll bar instead of the movie/tv item.

Also a variable on Plot Overlay delay would be cool (default is five seconds) if possible. Thanks again for the great work you do.

**Comment by jurialmunkey** [comment]
None of these requests are possible:

For 1 & 2, it isn't possible for skins to change what control is focused when the user is idle, so the item list remains focused when plot overlay auto displays. 

Skins can only change focused control when a user clicks a control or presses a direction against the edge of a control. That's why I can take control in info dialog - user presses up, so I send focus to a hidden scrollbar for the plot overlay textbox.

For 3, kodi visibility conditions don't accept user inputted skin variables. To have a variable, I would need a condition checking every possible user value and then adjusting the idle time based upon that. e.g. `<visible>[System.IdleTime(1) + Skin.String(PlotOverlayIdle,1] | [System.IdleTime(2) + Skin.String(PlotOverlayIdle,2] | [System.IdleTime(3) + Skin.String(PlotOverlayIdle,3] | [System.IdleTime(4) + Skin.String(PlotOverlayIdle,4] | [System.IdleTime(5) + Skin.String(PlotOverlayIdle,5] etc. etc. etc.</visible>`

If you want more control over plot overlay, bind a button on your remote to `SetFocus(9601)`
That will open the plot overlay on press and will give you control over scrolling.

**Comment by brentonv** [comment]
Thanks heaps for the detailed response. What about a timer? I find 5 seconds too short. Would that be ok?
