### ISSUE TITLE
[bug] Use poster for blur uses Season poster instead of Series poster.

### ISSUE THREAD

**Issue by spauldhaliwal** [jurialmunkey/skin.arctic.zephyr.2#37]
When using the option to use posters for blur, the skin currently uses the TV Season poster instead of the TV series poster. If the purpose of this option is to add consistency with the color of blue with what's selected on the screen, imo it makes more sense to use the TV Series poster. Reversing the following lines does the trick:
`<value condition="!String.IsEmpty(Container.ListItem.Art(poster))">$INFO[Container.ListItem.Art(poster)]</value>
<value condition="!String.IsEmpty(Container.ListItem.Art(tvshow.poster))">$INFO[Container.ListItem.Art(tvshow.poster)]</value>`

I've uploaded a video clip demonstrating the issue.

https://imgur.com/a/4tlgO91

**Comment by jurialmunkey** [comment]
It's because that is the order of artwork in the library. Season poster has to be preferenced, otherwise you don't get season poster artwork.

Can you try latest release (v0.9.29-a5) 
https://github.com/jurialmunkey/skin.arctic.zephyr.2/releases/tag/skin.arctic.zephyr.2-v0.9.29-alpha5

I've changed it so that the widgets should now show the season poster.

**Comment by spauldhaliwal** [comment]
That works. In general, I like the look of using the tv show poster instead of the season for the home screen widgets, though I totally understand that's a matter of opinion. Of course, season posters are more informative but from a design, perspective can often leave a lot to be desired so sticking to tv show artwork gives a more polished feel (I believe plex works this way for this reason). That being said, obviously that's a matter of opinion and with the latest fix, the blur colors consistently match the selected item at least!

**Comment by spauldhaliwal** [comment]
By the way, do you prefer bug/feature requests to come through GitHub or the forum?

**Comment by jurialmunkey** [comment]
> 
> 
> That works. In general, I like the look of using the tv show poster instead of the season for the home screen widgets, though I totally understand that's a matter of opinion. Of course, season posters are more informative but from a design perspective, can often leave a lot to be desired. So sticking to tv show artwork gives a more polished feel (I believe plex works this way for this reason). That being said, obviously that's a matter of opinion and with the latest fix, the blur colors consistently match the selected item at least!

Yeah I agree about tvshow posters being better for widgets. I'm just trying to avoid overly complex variables that only apply to the home screen (there are a ton of edge-cases that pop-up when applying different approaches to the home screen only. 

> 
> 
> By the way, do you prefer bug/feature requests to come through GitHub or the forum?

In terms of bugs and feature requests, github is preferred because it is much easier to keep track of things.
