### ISSUE TITLE
[Bug] Custom Search uses Poster Artwork no matter what

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.zephyr.2#39]
As you can see below, it appears that poster artwork is being used, no matter what the aspect is set to.

![image](https://user-images.githubusercontent.com/2319508/56854364-22621500-68ea-11e9-9377-a74e5365e739.png)
![image](https://user-images.githubusercontent.com/2319508/56854370-37d73f00-68ea-11e9-9b4b-6f8d9b1d1285.png)
![image](https://user-images.githubusercontent.com/2319508/56854350-e464f100-68e9-11e9-9457-b58ad36b5183.png)

**Comment by jurialmunkey** [comment]
Should be fixed as of v0.9.29-a4 https://github.com/jurialmunkey/skin.arctic.zephyr.2/commit/0734d94c054c172363781917eb553197841a77b3

Great to see someone using the custom search function! 
I'm hoping to compile some lists of ready made paths to have as immediately selectable from a folder in the action dialog. So any that you find, please add here https://github.com/jurialmunkey/skin.arctic.zephyr.2/issues/36

I'm also going to try and see if I can integrate the existing default searches within the customisation window so that it is possible to rearrange them.

**Comment by drinfernoo** [comment]
I would love to be able to rearrange them! I love this feature 😁 I saw your links for Spotify... if only it worked on Android boxes :( I'll try and see if I can figure out some working ones for good add-ons 👍
