### ISSUE TITLE
[Request] Add option to choose default rating provider. 

### ISSUE THREAD

**Issue by spauldhaliwal** [jurialmunkey/skin.arctic.zephyr.2#49]
It would be great to be able to choose manually who is providing our ratings so that the proper logo is displayed. For example, I use Plex Kodi Connect and my Plex server is set up to use rotten tomatoes for ratings. However this is just stored as a rating and so Kodi, or the skin, assumes by default that it's IMDB. If not using metadata utils omdb-feature, it would be great if we could just manually say that our ratings are coming from x-provider.

**Comment by jurialmunkey** [comment]
The problem is that different ratings might be used for different content (e.g. imdb for movies, tvdb for tvshows) - or even between different add-ons and the library. There isn't really anyway to tell where the rating is from.

I guess the solution is to *not* assume that the library rating is imdb and only use the library rating for the star rating. Everything else with a logo should come from skinhelper or listitemhelper.

**Comment by jurialmunkey** [comment]
See latest release. Made the changes in my comment above.
https://github.com/jurialmunkey/skin.arctic.zephyr.2/releases/tag/skin.arctic.zephyr.2-v0.9.32-alpha2

**Comment by spauldhaliwal** [comment]
Seems like the best choice. Thanks!
