### ISSUE TITLE
[Request] Extended Info button on OSD

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.zephyr.2#62]
Just as the title says. Hoping we can get that back, as I used it very often in Aura.

**Comment by vitorp07** [comment]
@jurialmunkey  If this can save you some time, I wrote a small addon for people using using skins without  which does exactly this

**Comment by vitorp07** [comment]
@jurialmunkey If this can save you some time, 
I wrote a small addon for people using skins that do not provide the ability to open extendedinfo dialog from the video osd, so that they can bind a key to launch my addon which then open extendedinfo dialog.
The addon takes care of pausing/unpausing the video which can be disabled via settings and also includes a setting to choose between tv show info dialog or episode info dialog if kodi version is at least 17.
If you are interested here is the link of the addon repo;
https://github.com/vitorp07/videoosd.extendedinfo.dialog
and here is the link of the post on Kodi's forum;
https://forum.kodi.tv/showthread.php?tid=160558&pid=2858049#pid2858049

**Comment by jurialmunkey** [comment]
Added.
