### ISSUE TITLE
Season Info 2 Scrolling Wierdness...

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/skin.arctic.zephyr.2#85]
I hadn't noticed it yet, but the new Season Info 2 viewtype is awesome and works really smoothly... except when scrolling *up* between seasons. When scrolling down from one season to another, it obviously scrolls from the last episode of the current season to the first episode of the next season... but when scrolling up, it scrolls from the first episode of the current season to the **first** episode of the previous season, rather than the last one. Is it possible to fix this?

**Comment by jurialmunkey** [comment]
Not possible (or at least I was unable to find a way when I made the view). The issue is that when moving up the list hasn't loaded yet, so setting focus to the last item in list sets the position to the last item in the *currently* visible season rather than the one that loads. For instance, say if the currently visible season has 7 episodes but the previous has 13 episodes, then scrolling up will set focus to the 7th out of 13 episodes - I figure going to the first episode is better than ending up somewhere randomly in the middle of the season. 

I can't set a delay because it is impossible to tell how long the list will take to load.
